name: zuny-real-estate-backend
services:
- name: strapi-api
  source_dir: backend
  github:
    repo: zordon/zuny-real-estate
    branch: main
    deploy_on_push: true
  run_command: yarn start
  build_command: yarn install && yarn build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 1337
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_CLIENT
    value: sqlite
  - key: DATABASE_FILENAME
    value: .tmp/data.db
  - key: HOST
    value: 0.0.0.0
  - key: PORT
    value: "1337"
  - key: APP_KEYS
    value: ${APP_KEYS} # Set this in DO dashboard
  - key: API_TOKEN_SALT
    value: ${API_TOKEN_SALT} # Set this in DO dashboard
  - key: ADMIN_JWT_SECRET
    value: ${ADMIN_JWT_SECRET} # Set this in DO dashboard
  - key: TRANSFER_TOKEN_SALT
    value: ${TRANSFER_TOKEN_SALT} # Set this in DO dashboard
  - key: JWT_SECRET
    value: ${JWT_SECRET} # Set this in DO dashboard 